name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (lightweight)
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest -r requirements.txt
      - name: Lint with Ruff
        run: ruff .
      - name: Format check with Black
        run: black --check .
      - name: Run tests
        run: pytest
